stims = [
  {
    "collection_name": "practice",
    "level_name": "1",
    "stimuli_set": "",
    "layout": [
      "######",
      "#  $.#",
      "#@ $.#",
      "#    #",
      "######"
    ],
    "width": 6,
    "height": 5,
    "start_position": { "x": 1, "y": 2 },
    "boxes": [
      { "x": 3, "y": 2, "state": "$" },
      { "x": 3, "y": 1, "state": "$" },
    ],
  }, {
    "collection_name": "practice",
    "level_name": "2",
    "stimuli_set": "",
    "layout": [
      "######",
      "#    #",
      "#*$ @#",
      "#. ###",
      "######",
    ],
    "width": 6,
    "height": 5,
    "start_position": { "x": 4, "y": 2 },
    "boxes": [
      { "x": 1, "y": 2, "state": "*" },
      { "x": 2, "y": 2, "state": "$" },
    ],
  },
  {
    "collection_name": "practice",
    "level_name": '3',
    "stimuli_set": "",
    "layout": ['  #####', '  #.  #', '###   #', '# $*$ #', '#   ###', '#@ .#', '#####'],
    "width": 7,
    "height": 7,
    "start_position": { "x": 1, "y": 5 },
    "boxes": [
      { "x": 2, "y": 3, "state": "$" },
      { "x": 3, "y": 3, "state": "*" },
      { "x": 4, "y": 3, "state": "$" }
    ],
  },
  { "stimuli_set": "A", "author_name": "david-w-skinner", "collection_name": "Microban", "level_name": 67, "width": 7, "height": 8, "layout": ["#####", "#   ##", "# #  #", "#@$*.##", "##  . #", " # $# #", " ##   #", "  #####"], "start_position": { "x": 1, "y": 3 }, "boxes": [{ "x": 2, "y": 3, "state": "$" }, { "x": 3, "y": 3, "state": "*" }, { "x": 3, "y": 5, "state": "$" }] },
  { "stimuli_set": "A", "author_name": "jacques-duthen", "collection_name": "Sokogen-990602-Levels", "level_name": 13, "width": 8, "height": 6, "layout": ["######", "#@   ##", "# .$* ##", "# #$.  #", "#      #", "########"], "start_position": { "x": 1, "y": 1 }, "boxes": [{ "x": 3, "y": 2, "state": "$" }, { "x": 4, "y": 2, "state": "*" }, { "x": 3, "y": 3, "state": "$" }] },
  { "stimuli_set": "A", "author_name": "jacques-duthen", "collection_name": "Sokogen-990602-Levels", "level_name": 32, "width": 7, "height": 7, "layout": ["#######", "##   ##", "## #.##", "#  $.##", "# # $ #", "#  * @#", "#######"], "start_position": { "x": 5, "y": 5 }, "boxes": [{ "x": 3, "y": 3, "state": "$" }, { "x": 4, "y": 4, "state": "$" }, { "x": 3, "y": 5, "state": "*" }] },
  { "stimuli_set": "A", "author_name": "jacques-duthen", "collection_name": "Sokogen-990602-Levels", "level_name": 18, "width": 7, "height": 7, "layout": ["#######", "#  ####", "#   ###", "#$ $@##", "#. #$ #", "#  . .#", "#######"], "start_position": { "x": 4, "y": 3 }, "boxes": [{ "x": 1, "y": 3, "state": "$" }, { "x": 3, "y": 3, "state": "$" }, { "x": 4, "y": 4, "state": "$" }] },
  { "stimuli_set": "A", "author_name": "david-w-skinner", "collection_name": "Microban", "level_name": 104, "width": 9, "height": 9, "layout": ["    #####", "#####   #", "#    $  #", "#  $#$#@#", "### #   #", "  # ... #", "  ###  ##", "    #  #", "    ####"], "start_position": { "x": 7, "y": 3 }, "boxes": [{ "x": 5, "y": 2, "state": "$" }, { "x": 3, "y": 3, "state": "$" }, { "x": 5, "y": 3, "state": "$" }] },
  { "stimuli_set": "A", "author_name": "jacques-duthen", "collection_name": "Sokogen-990602-Levels", "level_name": 38, "width": 8, "height": 6, "layout": ["#####", "#. .####", "#$$    #", "#@$#   #", "# .    #", "########"], "start_position": { "x": 1, "y": 3 }, "boxes": [{ "x": 1, "y": 2, "state": "$" }, { "x": 2, "y": 2, "state": "$" }, { "x": 2, "y": 3, "state": "$" }] },
  { "stimuli_set": "A", "author_name": "jacques-duthen", "collection_name": "Sokogen-990602-Levels", "level_name": 34, "width": 8, "height": 7, "layout": ["########", "##@ ####", "##$$   #", "#  $ # #", "# # ...#", "#   ####", "########"], "start_position": { "x": 2, "y": 1 }, "boxes": [{ "x": 2, "y": 2, "state": "$" }, { "x": 3, "y": 2, "state": "$" }, { "x": 3, "y": 3, "state": "$" }] },
  { "stimuli_set": "A", "author_name": "jacques-duthen", "collection_name": "Sokogen-990602-Levels", "level_name": 35, "width": 8, "height": 6, "layout": ["######", "#@ * ###", "# #    #", "#.$$.# #", "#      #", "########"], "start_position": { "x": 1, "y": 1 }, "boxes": [{ "x": 3, "y": 1, "state": "*" }, { "x": 2, "y": 3, "state": "$" }, { "x": 3, "y": 3, "state": "$" }] },
  { "stimuli_set": "B", "author_name": "david-w-skinner", "collection_name": "Microban", "level_name": 33, "width": 7, "height": 7, "layout": ["#######", "#. #  #", "#  $  #", "#. $#@#", "#  $  #", "#. #  #", "#######"], "start_position": { "x": 5, "y": 3 }, "boxes": [{ "x": 3, "y": 2, "state": "$" }, { "x": 3, "y": 3, "state": "$" }, { "x": 3, "y": 4, "state": "$" }] },
  { "stimuli_set": "B", "author_name": "jacques-duthen", "collection_name": "Sokogen-990602-Levels", "level_name": 19, "width": 6, "height": 6, "layout": ["######", "#@  .#", "#$$$ #", "#. # #", "#  . #", "######"], "start_position": { "x": 1, "y": 1 }, "boxes": [{ "x": 1, "y": 2, "state": "$" }, { "x": 2, "y": 2, "state": "$" }, { "x": 3, "y": 2, "state": "$" }] },
  { "stimuli_set": "B", "author_name": "jacques-duthen", "collection_name": "Sokogen-990602-Levels", "level_name": 17, "width": 7, "height": 7, "layout": ["#####", "#@  ###", "# $$$ #", "## ...#", "#   # #", "#     #", "#######"], "start_position": { "x": 1, "y": 1 }, "boxes": [{ "x": 2, "y": 2, "state": "$" }, { "x": 3, "y": 2, "state": "$" }, { "x": 4, "y": 2, "state": "$" }] },
  { "stimuli_set": "B", "author_name": "jacques-duthen", "collection_name": "Dimitri-and-Yorick", "level_name": 37, "width": 6, "height": 6, "layout": ["######", "# @$.#", "# $$.#", "#  #.#", "#    #", "######"], "start_position": { "x": 2, "y": 1 }, "boxes": [{ "x": 3, "y": 1, "state": "$" }, { "x": 2, "y": 2, "state": "$" }, { "x": 3, "y": 2, "state": "$" }] },
  { "stimuli_set": "B", "author_name": "david-w-skinner", "collection_name": "Microban", "level_name": 41, "width": 8, "height": 6, "layout": ["#######", "#     #", "#@$$$ ##", "#  #...#", "##    ##", " ######"], "start_position": { "x": 1, "y": 2 }, "boxes": [{ "x": 2, "y": 2, "state": "$" }, { "x": 3, "y": 2, "state": "$" }, { "x": 4, "y": 2, "state": "$" }] },
  { "stimuli_set": "B", "author_name": "jacques-duthen", "collection_name": "Sokogen-990602-Levels", "level_name": 6, "width": 8, "height": 7, "layout": [" #####", "##   ###", "# .# $@#", "#  # # #", "# *  $.#", "#    ###", "######"], "start_position": { "x": 6, "y": 2 }, "boxes": [{ "x": 5, "y": 2, "state": "$" }, { "x": 2, "y": 4, "state": "*" }, { "x": 5, "y": 4, "state": "$" }] },
  { "stimuli_set": "B", "author_name": "david-w-skinner", "collection_name": "Microban", "level_name": 48, "width": 8, "height": 8, "layout": ["######", "#  @ #", "#  # ##", "# .#  ##", "# .$$$ #", "# .#   #", "####   #", "   #####"], "start_position": { "x": 3, "y": 1 }, "boxes": [{ "x": 3, "y": 4, "state": "$" }, { "x": 4, "y": 4, "state": "$" }, { "x": 5, "y": 4, "state": "$" }] },
  { "stimuli_set": "B", "author_name": "jacques-duthen", "collection_name": "Sokogen-990602-Levels", "level_name": 39, "width": 9, "height": 7, "layout": ["######", "#    #", "# ## ##", "# . * ###", "## $ *  #", " #  #  @#", " ########"], "start_position": { "x": 7, "y": 5 }, "boxes": [{ "x": 4, "y": 3, "state": "*" }, { "x": 3, "y": 4, "state": "$" }, { "x": 5, "y": 4, "state": "*" }] },
  { "stimuli_set": "C", "author_name": "david-w-skinner", "collection_name": "Microban", "level_name": 26, "width": 6, "height": 8, "layout": [" #####", " # @ #", " #   #", "###$ #", "# ...#", "# $$ #", "###  #", "  ####"], "start_position": { "x": 3, "y": 1 }, "boxes": [{ "x": 3, "y": 3, "state": "$" }, { "x": 2, "y": 5, "state": "$" }, { "x": 3, "y": 5, "state": "$" }] },
  { "stimuli_set": "C", "author_name": "jacques-duthen", "collection_name": "Sokogen-990602-Levels", "level_name": 41, "width": 9, "height": 7, "layout": ["######", "#    #", "# ## ##", "# .$@.###", "## $$   #", " #  #.  #", " ########"], "start_position": { "x": 4, "y": 3 }, "boxes": [{ "x": 3, "y": 3, "state": "$" }, { "x": 3, "y": 4, "state": "$" }, { "x": 4, "y": 4, "state": "$" }] },
  { "stimuli_set": "C", "author_name": "david-w-skinner", "collection_name": "Microban", "level_name": 17, "width": 6, "height": 7, "layout": ["#####", "# @ #", "#...#", "#$$$##", "#    #", "#    #", "######"], "start_position": { "x": 2, "y": 1 }, "boxes": [{ "x": 1, "y": 3, "state": "$" }, { "x": 2, "y": 3, "state": "$" }, { "x": 3, "y": 3, "state": "$" }] },
  { "stimuli_set": "C", "author_name": "jacques-duthen", "collection_name": "Sokogen-990602-Levels", "level_name": 14, "width": 7, "height": 7, "layout": ["######", "#  . #", "# #. ##", "#  .  #", "# $$$ #", "#  # @#", "#######"], "start_position": { "x": 5, "y": 5 }, "boxes": [{ "x": 2, "y": 4, "state": "$" }, { "x": 3, "y": 4, "state": "$" }, { "x": 4, "y": 4, "state": "$" }] },
  { "stimuli_set": "C", "author_name": "aymeric-du-peloux", "collection_name": "Microcosmos", "level_name": 28, "width": 9, "height": 7, "layout": ["     ####", "    ##  #", "   ## . #", "#### $  #", "# $ $.@##", "#  .  ##", "#######"], "start_position": { "x": 6, "y": 4 }, "boxes": [{ "x": 5, "y": 3, "state": "$" }, { "x": 2, "y": 4, "state": "$" }, { "x": 4, "y": 4, "state": "$" }] },
  { "stimuli_set": "C", "author_name": "jacques-duthen", "collection_name": "Sokogen-990602-Levels", "level_name": 40, "width": 8, "height": 6, "layout": ["######", "#    ###", "# @#$  #", "# *.$  #", "# . #  #", "########"], "start_position": { "x": 2, "y": 2 }, "boxes": [{ "x": 4, "y": 2, "state": "$" }, { "x": 2, "y": 3, "state": "*" }, { "x": 4, "y": 3, "state": "$" }] },
  { "stimuli_set": "C", "author_name": "david-w-skinner", "collection_name": "Microban", "level_name": 43, "width": 9, "height": 9, "layout": ["     ####", "     # @#", "     #  #", "###### .#", "#   $  .#", "#  $$# .#", "#    ####", "###  #", "  ####"], "start_position": { "x": 7, "y": 1 }, "boxes": [{ "x": 4, "y": 4, "state": "$" }, { "x": 3, "y": 5, "state": "$" }, { "x": 4, "y": 5, "state": "$" }] },
  { "stimuli_set": "C", "author_name": "jacques-duthen", "collection_name": "Sokogen-990602-Levels", "level_name": 46, "width": 7, "height": 7, "layout": ["#######", "##  ###", "## .$ #", "# $$  #", "# #. .#", "#@  ###", "#######"], "start_position": { "x": 1, "y": 5 }, "boxes": [{ "x": 4, "y": 2, "state": "$" }, { "x": 2, "y": 3, "state": "$" }, { "x": 3, "y": 3, "state": "$" }] }
]